# Лабораторная работа №3

## Баканов Сергей ИБМ3-65Б

In [454]:
import numpy as np
import pandas as pd
from sklearn.datasets import *
import seaborn as sns
import matplotlib.pyplot as plt

In [455]:
data = pd.read_csv("smartphones.csv")

In [456]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 980 entries, 0 to 979
Data columns (total 22 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   brand_name                 980 non-null    str
 1   model                      980 non-null    str
 2   price                      980 non-null    int64
 3   avg_rating                 879 non-null    float64
 4   5G_or_not                  980 non-null    int64
 5   processor_brand            960 non-null    str
 6   num_cores                  974 non-null    float64
 7   processor_speed            938 non-null    float64
 8   battery_capacity           969 non-null    float64
 9   fast_charging_available    980 non-null    int64
 10  fast_charging              769 non-null    float64
 11  ram_capacity               980 non-null    int64
 12  internal_memory            980 non-null    int64
 13  screen_size                980 non-null    float64
 14  refresh_rate               980 non-null    int64
 15  num_rear_cameras           980 non-null    int64
 16  os                         966 non-null    str
 17  primary_camera_rear        980 non-null    float64
 18  primary_camera_front       975 non-null    float64
 19  extended_memory_available  980 non-null    int64
 20  resolution_height          980 non-null    int64
 21  resolution_width           980 non-null    int64
dtypes: float64(8), int64(10), str(4)
memory usage: 168.6 KB

In [457]:
data.head()

,brand_name,model,price,avg_rating,5G_or_not,processor_brand,num_cores,processor_speed,battery_capacity,fast_charging_available,...,internal_memory,screen_size,refresh_rate,num_rear_cameras,os,primary_camera_rear,primary_camera_front,extended_memory_available,resolution_height,resolution_width
0,apple,Apple iPhone 11,38999,7.3,0,bionic,6.0,2.65,3110.0,0,...,64,6.1,60,2,ios,12.0,12.0,0,1792,828
1,apple,Apple iPhone 11 (128GB),46999,7.5,0,bionic,6.0,2.65,3110.0,0,...,128,6.1,60,2,ios,12.0,12.0,0,1792,828
2,apple,Apple iPhone 11 Pro Max,109900,7.7,0,bionic,6.0,2.65,3500.0,1,...,64,6.5,60,3,ios,12.0,12.0,0,2688,1242
3,apple,Apple iPhone 12,51999,7.4,1,bionic,6.0,3.10,NaN,0,...,64,6.1,60,2,ios,12.0,12.0,0,2532,1170
4,apple,Apple iPhone 12 (128GB),55999,7.5,1,bionic,6.0,3.10,NaN,0,...,128,6.1,60,2,ios,12.0,12.0,0,2532,1170

In [458]:
data.describe()

,price,avg_rating,5G_or_not,num_cores,processor_speed,battery_capacity,fast_charging_available,fast_charging,ram_capacity,internal_memory,screen_size,refresh_rate,num_rear_cameras,primary_camera_rear,primary_camera_front,extended_memory_available,resolution_height,resolution_width
count,980.000000,879.000000,980.000000,974.000000,938.000000,969.000000,980.000000,769.000000,980.000000,980.000000,980.000000,980.000000,980.000000,980.000000,975.000000,980.000000,980.000000,980.000000
mean,32520.504082,7.825825,0.560204,7.772074,2.427217,4817.748194,0.854082,46.126138,6.560204,141.036735,6.536765,92.256122,2.814286,50.319286,16.589744,0.630612,2214.663265,1075.852041
std,39531.812669,0.740285,0.496616,0.836845,0.464090,1009.540054,0.353205,34.277870,2.744378,107.134516,0.349162,28.988052,0.776441,33.000968,10.876944,0.482885,516.484254,290.164931
min,3499.000000,6.000000,0.000000,4.000000,1.200000,1821.000000,0.000000,10.000000,1.000000,8.000000,3.540000,60.000000,1.000000,2.000000,0.000000,0.000000,480.000000,480.000000
25%,12999.000000,7.400000,0.000000,8.000000,2.050000,4500.000000,1.000000,18.000000,4.000000,64.000000,6.500000,60.000000,2.000000,24.000000,8.000000,0.000000,1612.000000,1080.000000
50%,19994.500000,8.000000,1.000000,8.000000,2.300000,5000.000000,1.000000,33.000000,6.000000,128.000000,6.580000,90.000000,3.000000,50.000000,16.000000,1.000000,2400.000000,1080.000000
75%,35491.500000,8.400000,1.000000,8.000000,2.840000,5000.000000,1.000000,66.000000,8.000000,128.000000,6.670000,120.000000,3.000000,64.000000,16.000000,1.000000,2408.000000,1080.000000
max,650000.000000,8.900000,1.000000,8.000000,3.220000,22000.000000,1.000000,240.000000,18.000000,1024.000000,8.030000,240.000000,4.000000,200.000000,60.000000,1.000000,3840.000000,2460.000000

In [459]:
for col in data.columns:
    if data[col].dtype in ['int64', 'float64']:
        data[col].fillna(data[col].mean())
    else:
        data[col].dropna()

In [460]:
numeric_cols = data.select_dtypes(include=['int64', 'float64']).columns.tolist()
categorical_cols = data.select_dtypes(include=['str']).columns.tolist()

In [461]:
target = "price"
numeric_cols.remove("price")

In [462]:
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.impute import SimpleImputer
numeric_transformer = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='median')),
    ('scaler', StandardScaler())
])
categorical_transformer = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='most_frequent')),
    ('encoder', OneHotEncoder(handle_unknown='ignore', sparse_output=False))
])
preprocessor = ColumnTransformer(
    transformers=[
        ('num', numeric_transformer, numeric_cols),
        ('cat', categorical_transformer, categorical_cols)
    ],
    remainder='drop'
)

In [463]:
from sklearn.model_selection import train_test_split

X = data.drop(target, axis = 1)
y = data[target]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state = 333)

In [464]:
from sklearn.neighbors import KNeighborsRegressor
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

knn = KNeighborsRegressor(n_neighbors=5)

model = Pipeline(steps=[
    ('preprocessor', preprocessor),
    ('regressor', knn)
])

model.fit(X_train, y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('num',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='median')),
                                                                  ('scaler',
                                                                   StandardScaler())]),
                                                  ['avg_rating', '5G_or_not',
                                                   'num_cores',
                                                   'processor_speed',
                                                   'battery_capacity',
                                                   'fast_charging_available',
                                                   'fast_charging',
                                                   'ram_capacity',
                                                   'internal_memory',
                                                   'screen_size',
                                                   'refresh_rate',
                                                   'num_rear...,
                                                   'primary_camera_rear',
                                                   'primary_camera_front',
                                                   'extended_memory_available',
                                                   'resolution_height',
                                                   'resolution_width']),
                                                 ('cat',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='most_frequent')),
                                                                  ('encoder',
                                                                   OneHotEncoder(handle_unknown='ignore',
                                                                                 sparse_output=False))]),
                                                  ['brand_name', 'model',
                                                   'processor_brand',
                                                   'os'])])),
                ('regressor', KNeighborsRegressor())])

In [465]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

y_pred = model.predict(X_test)

mae = mean_absolute_error(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
rmse = np.sqrt(mse)
r2 = r2_score(y_test, y_pred)

mae, mse, rmse, r2

(8050.2795918367365,
 222293543.9093878,
 np.float64(14909.5118601981),
 0.8278541656500935)

In [466]:
from sklearn.model_selection import cross_val_score

cv_scores = cross_val_score(model, X_train, y_train, cv=5, scoring='r2')
cv_scores

array([0.31467549, 0.87458424, 0.15729853, 0.67828451, 0.56953513])

In [467]:
knn = KNeighborsRegressor(n_neighbors=2)

model = Pipeline(steps=[
    ('preprocessor', preprocessor),
    ('regressor', knn)
])

model.fit(X_train, y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('num',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='median')),
                                                                  ('scaler',
                                                                   StandardScaler())]),
                                                  ['avg_rating', '5G_or_not',
                                                   'num_cores',
                                                   'processor_speed',
                                                   'battery_capacity',
                                                   'fast_charging_available',
                                                   'fast_charging',
                                                   'ram_capacity',
                                                   'internal_memory',
                                                   'screen_size',
                                                   'refresh_rate',
                                                   'num_rear...
                                                   'primary_camera_rear',
                                                   'primary_camera_front',
                                                   'extended_memory_available',
                                                   'resolution_height',
                                                   'resolution_width']),
                                                 ('cat',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='most_frequent')),
                                                                  ('encoder',
                                                                   OneHotEncoder(handle_unknown='ignore',
                                                                                 sparse_output=False))]),
                                                  ['brand_name', 'model',
                                                   'processor_brand',
                                                   'os'])])),
                ('regressor', KNeighborsRegressor(n_neighbors=2))])

In [468]:
y_pred_final = model.predict(X_test)

mae_f = mean_absolute_error(y_test, y_pred_final)
mse_f = mean_squared_error(y_test, y_pred_final)
rmse_f = np.sqrt(mse_f)
r2_f = r2_score(y_test, y_pred_final)

mae, mae_f

(8050.2795918367365, 6801.821428571428)

In [469]:
mse, mse_f

(222293543.9093878, 166056436.09183672)

In [470]:
rmse, rmse_f

(np.float64(14909.5118601981), np.float64(12886.288685724712))

In [471]:
r2, r2_f

(0.8278541656500935, 0.8714046155481084)

In [472]:
from sklearn.model_selection import GridSearchCV, RandomizedSearchCV, KFold, ShuffleSplit

kf = KFold(n_splits=5, shuffle=True, random_state=42)

ss = ShuffleSplit(n_splits=5, test_size=0.2, random_state=42)

param_grid = {'regressor__n_neighbors': list(range(1, 21))}

grid = GridSearchCV(model, param_grid, cv=kf, scoring='r2')
grid.fit(X_train, y_train)

random_search = RandomizedSearchCV(model, param_grid, n_iter=10, cv=ss, scoring='r2', random_state=42)
random_search.fit(X_train, y_train)

RandomizedSearchCV(cv=ShuffleSplit(n_splits=5, random_state=42, test_size=0.2, train_size=None),
                   estimator=Pipeline(steps=[('preprocessor',
                                              ColumnTransformer(transformers=[('num',
                                                                               Pipeline(steps=[('imputer',
                                                                                                SimpleImputer(strategy='median')),
                                                                                               ('scaler',
                                                                                                StandardScaler())]),
                                                                               ['avg_rating',
                                                                                '5G_or_not',
                                                                                'num_cores',
                                                                                'processor_speed',
                                                                                'battery_capacity',
                                                                                'fast_char...
                                                                               Pipeline(steps=[('imputer',
                                                                                                SimpleImputer(strategy='most_frequent')),
                                                                                               ('encoder',
                                                                                                OneHotEncoder(handle_unknown='ignore',
                                                                                                              sparse_output=False))]),
                                                                               ['brand_name',
                                                                                'model',
                                                                                'processor_brand',
                                                                                'os'])])),
                                             ('regressor',
                                              KNeighborsRegressor(n_neighbors=2))]),
                   param_distributions={'regressor__n_neighbors': [1, 2, 3, 4,
                                                                   5, 6, 7, 8,
                                                                   9, 10, 11,
                                                                   12, 13, 14,
                                                                   15, 16, 17,
                                                                   18, 19,
                                                                   20]},
                   random_state=42, scoring='r2')

In [473]:
best_grid_model = grid.best_estimator_

best_rand_model = random_search.best_estimator_

y_pred_grid = best_grid_model.predict(X_test)
y_pred_rand = best_rand_model.predict(X_test)

mae_grid = mean_absolute_error(y_test, y_pred_grid)
mse_grid = mean_squared_error(y_test, y_pred_grid)
rmse_grid = np.sqrt(mse_grid)
r2_grid = r2_score(y_test, y_pred_grid)

mae_rand = mean_absolute_error(y_test, y_pred_rand)
mse_rand = mean_squared_error(y_test, y_pred_rand)
rmse_rand = np.sqrt(mse_rand)
r2_rand = r2_score(y_test, y_pred_rand)

In [474]:
mae_grid, mae_rand

(8224.395408163266, 8166.298469387755)

In [475]:
mse_grid, mse_rand

(258744105.6685268, 241722691.14186507)

In [476]:
rmse_grid, rmse_rand

(np.float64(16085.524724687311), np.float64(15547.433586990011))

In [477]:
r2_grid, r2_rand

(0.7996265695796132, 0.8128080842290094)